version: "3.9"  # optional since v1.27.0
services:
  postgresql:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - c:\\developer\\bin\\postgresql\\data:/var/lib/postgresql/data
